### ISSUE TITLE
doesn't work with files with files with .md extension

### ISSUE THREAD

**Issue by ghost** [lehoff/gitlab-wiki-rename#1]
Doesn't work with files with files with .md extension.
I had to modify the script myself to replace .markdown with md. Would you kindly add support to the case of .md? :))

Thanks for the pretty script :))

**Comment by adam-edison** [comment]
@lordadamson I've written a second loop that does the exact same thing with *.md in that script, solved the problem for me. I'll attempt a pull request.

**Comment by lehoff** [comment]
@adam-edison has fixed this in #2, so I will close this one. Sorry for not paying attention to this for so long - I missed the original issue somehow.
